In [4]:
import torch

"""
It has an extensive choice of tools and libraries that support Computer Vision, Natural Language Processing(NLP), and 
many more ML programs. recognize the relationship between words)
Python program using PyTorch for defining tensors fit a two-layer network to random data and calculating the loss.
"""

print(torch.__version__)

2.0.1+cpu


In [15]:
##initializing Tensor
device="cuda" if torch.cuda.is_available() else "cpu"
my_tensor = torch.tensor([[1,2,3],[4,5,6]], dtype=torch.float32, device=device, requires_grad=True)

print(my_tensor)
print(my_tensor.dtype)
print(my_tensor.device)
print(my_tensor.shape)
print(my_tensor.requires_grad)


tensor([[1., 2., 3.],
        [4., 5., 6.]], requires_grad=True)
torch.float32
cpu
torch.Size([2, 3])
True


In [41]:
# Other common initialization methods
x1= torch.empty(size=(3,3))
"""
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
"""

x2= torch.zeros((3,3))
"""
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
"""

x3= torch.rand((3,3))
"""
tensor([[0.8156, 0.5082, 0.8837],
        [0.5388, 0.7806, 0.6653],
        [0.3834, 0.2005, 0.6963]])
"""

x4= torch.ones((3,3))
"""
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
"""

x5= torch.eye(3,3)
"""
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
"""

x6= torch.arange(start=0, end=5, step=1)
"""
tensor([0, 1, 2, 3, 4])
"""

x7= torch.linspace(start=0.1, end=2, steps=9)
"""
tensor([0.1000, 0.3375, 0.5750, 0.8125, 1.0500, 1.2875, 1.5250, 1.7625, 2.0000])
"""

x8= torch.empty(size=(1,5)).normal_(mean=0, std=1)
"""
tensor([[ 0.3494,  0.3771,  0.8429,  0.4100, -0.0471]])
"""

x9= torch.empty(size=(1,5)).uniform_(0,1)
"""
tensor([[0.3921, 0.1638, 0.1746, 0.2933, 0.2344]])
"""

x10= torch.diag(torch.ones(3))
"""
torch.diag() is a function that constructs a diagonal matrix from the given input tensor. 
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
"""


print(x10)



tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
