In [2]:
import torch

"""
It has an extensive choice of tools and libraries that support Computer Vision, Natural Language Processing(NLP), and 
many more ML programs. recognize the relationship between words)
Python program using PyTorch for defining tensors fit a two-layer network to random data and calculating the loss.
"""

print(torch.__version__)

2.0.1+cpu


In [3]:
##initializing Tensor
device="cuda" if torch.cuda.is_available() else "cpu"
my_tensor = torch.tensor([[1,2,3],[4,5,6]], dtype=torch.float32, device=device, requires_grad=True)

print(my_tensor)
print(my_tensor.dtype)
print(my_tensor.device)
print(my_tensor.shape)
print(my_tensor.requires_grad)


tensor([[1., 2., 3.],
        [4., 5., 6.]], requires_grad=True)
torch.float32
cpu
torch.Size([2, 3])
True


In [4]:
# Other common initialization methods
x1= torch.empty(size=(3,3))
"""
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
"""

x2= torch.zeros((3,3))
"""
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
"""

x3= torch.rand((3,3))
"""
tensor([[0.8156, 0.5082, 0.8837],
        [0.5388, 0.7806, 0.6653],
        [0.3834, 0.2005, 0.6963]])
"""

x4= torch.ones((3,3))
"""
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
"""

x5= torch.eye(3,3)
"""
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
"""

x6= torch.arange(start=0, end=5, step=1)
"""
tensor([0, 1, 2, 3, 4])
"""

x7= torch.linspace(start=0.1, end=2, steps=9)
"""
tensor([0.1000, 0.3375, 0.5750, 0.8125, 1.0500, 1.2875, 1.5250, 1.7625, 2.0000])
"""

x8= torch.empty(size=(1,5)).normal_(mean=0, std=1)
"""
tensor([[ 0.3494,  0.3771,  0.8429,  0.4100, -0.0471]])
"""

x9= torch.empty(size=(1,5)).uniform_(0,1)
"""
tensor([[0.3921, 0.1638, 0.1746, 0.2933, 0.2344]])
"""

x10= torch.diag(torch.ones(3))
"""
torch.diag() is a function that constructs a diagonal matrix from the given input tensor. 
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
"""


print(x10)



tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


In [12]:
#how to initialize and convert tensors to other types (int, float, double)
tensor = torch.arange(4)
print(tensor)
print(tensor.bool()) #boolean True/False
print(tensor.short()) #int16
print(tensor.long()) #int64 (important)
print(tensor.half()) #float16
print(tensor.float()) #float32 (important)
print(tensor.double()) #float64

tensor([0, 1, 2, 3])
tensor([False,  True,  True,  True])
tensor([0, 1, 2, 3], dtype=torch.int16)
tensor([0, 1, 2, 3])
tensor([0., 1., 2., 3.], dtype=torch.float16)
tensor([0., 1., 2., 3.])
tensor([0., 1., 2., 3.], dtype=torch.float64)


In [16]:
#Array to tensor Conversion and vice-versa
import numpy as np
np_array = np.zeros((5,5))
print(np_array)
tensor = torch.from_numpy(np_array)
print(tensor)
np_array_back = tensor.numpy()
print(np_array_back)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]], dtype=torch.float64)
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [42]:
#Tensor Math & Comparison Operations
x = torch.tensor([1,2,3])
y=torch.tensor([9,8,7])

#Addition
z1=torch.empty(3)
torch.add(x,y,out=z1)
print(z1)

z2=torch.add(x,y)
print(z2)

z=x+y
print(z)

#Subtraction
z=x-y

#Division
z = torch.true_divide(x,y)

print("-----------------------------")
#inplace operations
t1=torch.zeros(3)
print(t1)
t1.add_(x)
print(t1)
t1+=x #t=t+x
print(t1)
"""
tensor([0., 0., 0.])
tensor([1., 2., 3.])
tensor([2., 4., 6.])
"""

print("-----------------------------")
#Exponentiation
z=x.pow(2)
print(z) #z=x^2

print("-----------------------------")
#simple comparison
z1 = x>0
z2 = x<0
print(z1)

print("-----------------------------")
#Matrix Multiplication
x1=torch.rand((2,5))
x2=torch.rand((5,3))
x3=torch.mm(x1,x2)
x4=x1.mm(x2)
print(x3)
print(x4)
print(x3==x4)

print("-----------------------------")
#matrix exponentiation
matrix_exp = torch.rand(5,5)
print(matrix_exp.matrix_power(3))

print("-----------------------------")
#element wise mult.
z=x*y
print(z)

print("-----------------------------")
# dot product
z = torch.dot(x,y)
print(z)



tensor([10., 10., 10.])
tensor([10, 10, 10])
tensor([10, 10, 10])
-----------------------------
tensor([0., 0., 0.])
tensor([1., 2., 3.])
tensor([2., 4., 6.])
-----------------------------
tensor([1, 4, 9])
-----------------------------
tensor([True, True, True])
-----------------------------
tensor([[0.9959, 0.9109, 1.0262],
        [2.0167, 1.2918, 1.4539]])
tensor([[0.9959, 0.9109, 1.0262],
        [2.0167, 1.2918, 1.4539]])
tensor([[True, True, True],
        [True, True, True]])
-----------------------------
tensor([[1.9478, 1.6075, 2.4810, 2.9699, 1.0305],
        [2.7007, 2.1354, 3.3142, 3.7972, 1.3692],
        [3.3149, 2.6221, 4.0909, 4.5908, 1.5071],
        [2.6780, 2.1617, 3.3195, 3.8272, 1.4424],
        [2.1022, 1.6157, 2.3755, 2.9176, 1.1901]])
-----------------------------
tensor([ 9, 16, 21])
-----------------------------
tensor(46)
-----------------------------
tensor([[[5.1267, 5.2782, 4.1132,  ..., 3.2881, 4.9251, 5.2957],
         [6.2456, 5.5825, 4.8629,  ..., 4.3

In [43]:
print("-----------------------------")
# Batch Matrix Multiplication
batch = 32
n=10
m=20
p=30

tensor1 = torch.rand((batch,n,m))
print(tensor1)
tensor2 = torch.rand((batch,m,p))
print(tensor2)
out_bmm = torch.bmm(tensor1,tensor2) #(batch,n,p)
print(out_bmm)

-----------------------------
tensor([[[0.3261, 0.5416, 0.0033,  ..., 0.5979, 0.6389, 0.2050],
         [0.9403, 0.6956, 0.9694,  ..., 0.3629, 0.0413, 0.2487],
         [0.3871, 0.8399, 0.9203,  ..., 0.8308, 0.1271, 0.2599],
         ...,
         [0.1571, 0.1961, 0.0178,  ..., 0.9205, 0.5608, 0.0213],
         [0.7967, 0.6786, 0.0385,  ..., 0.1448, 0.1678, 0.7287],
         [0.1140, 0.8678, 0.3164,  ..., 0.3878, 0.9285, 0.0601]],

        [[0.1427, 0.9159, 0.1636,  ..., 0.9238, 0.3848, 0.9162],
         [0.0821, 0.8183, 0.8511,  ..., 0.1967, 0.1390, 0.7022],
         [0.7436, 0.5789, 0.1006,  ..., 0.6331, 0.1099, 0.8979],
         ...,
         [0.2077, 0.6014, 0.9732,  ..., 0.0348, 0.7231, 0.6928],
         [0.0643, 0.4632, 0.6202,  ..., 0.4576, 0.5869, 0.9446],
         [0.1000, 0.5531, 0.0219,  ..., 0.9096, 0.4271, 0.3963]],

        [[0.7026, 0.5764, 0.8544,  ..., 0.8111, 0.6709, 0.0223],
         [0.7748, 0.5295, 0.8228,  ..., 0.8272, 0.7359, 0.5820],
         [0.8686, 0.3025, 0.

In [46]:
#Examble of Broadcasting
x1=torch.rand((5,5))
x2=torch.rand((1,5))

print(x1)
print(x2)

x3=x1-x2
print(x3)
x4=x1 ** x2
print(x4)

tensor([[0.4592, 0.5419, 0.9555, 0.1624, 0.8424],
        [0.9012, 0.6013, 0.0572, 0.5856, 0.8550],
        [0.0559, 0.2908, 0.8955, 0.9250, 0.3951],
        [0.8237, 0.7366, 0.4791, 0.2407, 0.5614],
        [0.1636, 0.6426, 0.7882, 0.4569, 0.6149]])
tensor([[0.8071, 0.2254, 0.8650, 0.0590, 0.5116]])
tensor([[-0.3478,  0.3165,  0.0904,  0.1034,  0.3308],
        [ 0.0941,  0.3758, -0.8078,  0.5265,  0.3435],
        [-0.7511,  0.0654,  0.0305,  0.8660, -0.1165],
        [ 0.0167,  0.5111, -0.3859,  0.1817,  0.0499],
        [-0.6435,  0.4171, -0.0768,  0.3979,  0.1034]])
tensor([[0.5336, 0.8710, 0.9613, 0.8983, 0.9160],
        [0.9194, 0.8916, 0.0842, 0.9689, 0.9230],
        [0.0975, 0.7570, 0.9090, 0.9954, 0.6218],
        [0.8551, 0.9334, 0.5292, 0.9194, 0.7443],
        [0.2320, 0.9051, 0.8139, 0.9548, 0.7798]])


In [60]:
# other useful tensor operations
x = torch.tensor([100,12,30])
y=torch.tensor([9,8,7])

sum_x = torch.sum(x, dim=0)
print(sum_x)

values,indicates =torch.max(x,dim=0)
print(values)
print(indicates)

values,indicates =torch.min(x,dim=0)
print(values)
print(indicates)

abs_x = torch.abs(x)
print(abs_x)

z = torch.argmax(x, dim=0)
z1 = torch.argmin(x, dim=0)
print(z)
print(z1)

mean_x = torch.mean(x.float(), dim=0)
z = torch.eq(x,y)
print(z)

sorted_y, indices = torch.sort(y, dim=0, descending=False)
print(sorted_y)
print(indices)

tensor(142)
tensor(100)
tensor(0)
tensor(12)
tensor(1)
tensor([100,  12,  30])
tensor(0)
tensor(1)
tensor([False, False, False])
tensor([7, 8, 9])
tensor([2, 1, 0])


In [66]:
z= torch.clamp(x,min=0)
print(z)
x=torch.tensor([1,0,1,1,1], dtype=torch.bool)
z1=torch.any(x)
z2=torch.all(x)

print(z1)
print(z2)

tensor([1, 0, 1, 1, 1])
tensor(True)
tensor(False)


In [71]:
##Tensor Indexing
batch_size = 10
features = 25
x = torch.rand((batch_size, features))

print(x[0].shape) #x[0,:]
print(x[:,0])
print(x[2,0:10])


torch.Size([25])
tensor([0.4391, 0.9678, 0.6426, 0.4236, 0.9825, 0.9355, 0.7972, 0.3196, 0.6735,
        0.5864])
tensor([0.6426, 0.7870, 0.8218, 0.4196, 0.9885, 0.2740, 0.1319, 0.5043, 0.0621,
        0.0887])


In [83]:
#fancy indexing
x= torch.arange(10)
indices = [2,5,8]
print(x[indices])

x=torch.rand((3,5))
print(x)

 

tensor([2, 5, 8])
tensor([[0.3691, 0.1706, 0.0649, 0.1515, 0.1876],
        [0.9741, 0.9906, 0.2242, 0.9740, 0.0461],
        [0.8948, 0.1059, 0.9822, 0.6974, 0.0741]])
tensor([1, 0])
tensor([4, 0])
tensor([0.0461, 0.3691])
torch.Size([2])


In [90]:
# More Advance Indexing
x = torch.arange(10)
print(x[(x<2) | (x>8)])
print(x[(x<2) & (x<8)])
print(x[x.remainder(2)==0])

tensor([0, 1, 9])
tensor([0, 1])
tensor([0, 2, 4, 6, 8])


In [93]:
#useful operations
x = torch.arange(10)
print(torch.where(x>5,x,x*2)) #if?y:N
print(torch.tensor([0,0,1,2,2,3,4]).unique())
print(x.ndimension())
print(x.numel())

tensor([ 0,  2,  4,  6,  8, 10,  6,  7,  8,  9])
tensor([0, 1, 2, 3, 4])
1
10


In [107]:
#reshaping
x=torch.arange(9)
x_3x3 = x.view(3,3) #allocate memory
y_3x3 = x.reshape(3,3)  #save memory
print(x_3x3)
print(y_3x3)

y=x_3x3.t() #row to colom swap
print(y)
print(y.contiguous().view(9))   #make it single vector

x1=torch.rand((2,5))
x2=torch.rand((2,5))

print(torch.cat((x1,x2), dim=0).shape)
print(torch.cat((x1,x2), dim=1).shape)

z=x1.view(-1)
print(z.shape)

batch=64
x = torch.rand((batch,2,5))
print(x)
print("--------------------")
z = x.view(batch,-1)
print(z)
print(z.shape)


tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
tensor([[0, 3, 6],
        [1, 4, 7],
        [2, 5, 8]])
tensor([0, 3, 6, 1, 4, 7, 2, 5, 8])
torch.Size([4, 5])
torch.Size([2, 10])
torch.Size([10])
tensor([[[4.9820e-01, 2.5019e-02, 6.6935e-01, 2.9870e-01, 8.0325e-01],
         [3.2394e-01, 3.1330e-01, 4.6409e-01, 7.8112e-02, 8.5268e-01]],

        [[5.4993e-01, 9.7688e-01, 6.6193e-01, 1.8739e-01, 1.0301e-01],
         [9.7193e-03, 4.1621e-01, 9.3563e-01, 4.0887e-01, 2.5019e-01]],

        [[5.9586e-01, 9.2797e-01, 3.4732e-01, 4.8150e-01, 8.3081e-02],
         [5.7524e-01, 7.1256e-01, 3.1708e-01, 2.1021e-01, 8.9526e-01]],

        [[4.0935e-01, 9.6987e-01, 7.4208e-01, 4.8812e-01, 9.3496e-01],
         [5.5971e-01, 2.6323e-01, 8.3704e-01, 2.3095e-01, 7.5276e-01]],

        [[4.7402e-01, 4.4666e-01, 4.8541e-01, 9.6193e-01, 6.7902e-01],
         [3.3606e-01, 4.4141e-01, 5.3456e-01, 8.4278e-01, 3.1317e-01]],

        [[4.83

In [111]:
x = torch.rand((100,2,5))
z=x.permute(0,2,1)
print(z.shape)

torch.Size([100, 5, 2])


In [121]:
x = torch.arange(10)
print(x.unsqueeze(0).shape)
print(x.unsqueeze(1).shape)
x=torch.arange(10).unsqueeze(0).unsqueeze(1) #1x1x10

z=x.squeeze(0)
print(z.shape)

torch.Size([1, 10])
torch.Size([10, 1])
torch.Size([1, 10])
